backend:
  name: github
  repo: binawadlaser/binawadlaser
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "products"
    label: "المنتجات والأعمال"
    folder: "content/products"
    create: true
    fields:
      - {label: "عنوان المنتج", name: "title", widget: "string"}
      - {
          label: "تصنيف/قسم المنتج", 
          name: "category", 
          widget: "select", 
          options: ["ميداليات", "دروع وتكريم", "صناديق وهدايا", "ديكورات وتوزيعات", "أخرى"]
        }
      - {label: "الصورة", name: "image", widget: "image"}
      - {label: "الوصف", name: "description", widget: "text", required: false}
